# Generated by Django 5.0.1 on 2024-02-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-created_at',), 'verbose_name': 'Mualif', 'verbose_name_plural': 'Mualiflar'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
    ]
