# Generated by Django 5.0.1 on 2024-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_alter_author_options_remove_author_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='book_file/%Y/%m/%d', verbose_name='Kitobning Audio Shakli'),
        ),
        migrations.AddField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yuklab Olishlar Soni'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_file/%Y/%m/%d', verbose_name='Kitobninng PDF Shakli'),
        ),
    ]
